sources:
  - repoURL: https://publicstaticdevnull.github.io/platform-apps/
    chart: postgresql
    targetRevision: "*"
    helm:
      valueFiles:
        - $values/postgres/values.yaml

  - repoURL: https://github.com/publicstaticdevnull/platform-apps.git
    targetRevision: main
    ref: values