applications:
  echo-server:
    namespace: argocd
    project: platform-apps
    sources:
      - repoURL: https://publicstaticdevnull.github.io/platform-apps/
        chart: echo-server
        targetRevision: "*"
        helm:
          valueFiles:
            - $values/echo-server/values.yaml

      - repoURL: https://github.com/publicstaticdevnull/platform-apps.git
        targetRevision: main
        ref: values

    destination:
      server: https://kubernetes.default.svc
      namespace: platform-apps

    syncPolicy:
      syncOptions:
        - CreateNamespace=true
  grafana:
    namespace: argocd
    project: platform-observability
    sources:
      - repoURL: https://publicstaticdevnull.github.io/platform-observability/
        chart: grafana
        targetRevision: "*"
        helm:
          valueFiles:
            - $values/grafana/values.yaml

      - repoURL: https://github.com/publicstaticdevnull/platform-observability.git
        targetRevision: main
        ref: values

    destination:
      server: https://kubernetes.default.svc
      namespace: monitoring

    syncPolicy:
      syncOptions:
        - CreateNamespace=true
  loki:
    namespace: argocd
    project: platform-observability
    sources:
      - repoURL: https://publicstaticdevnull.github.io/platform-observability/
        chart: loki
        targetRevision: "*"
        helm:
          valueFiles:
            - $values/loki/values.yaml
      - repoURL: https://github.com/publicstaticdevnull/platform-observability.git
        targetRevision: pre-prod
        ref: values

    destination:
      server: https://kubernetes.default.svc
      namespace: monitoring

    syncPolicy:
      syncOptions:
        - CreateNamespace=true
  postgres:
    namespace: argocd
    project: platform-apps
    sources:
      - repoURL: https://publicstaticdevnull.github.io/platform-apps/
        chart: postgresql
        targetRevision: "*"
        helm:
          valueFiles:
            - $values/postgres/values.yaml

      - repoURL: https://github.com/publicstaticdevnull/platform-apps.git
        targetRevision: main
        ref: values

    destination:
      server: https://kubernetes.default.svc
      namespace: platform-apps

    syncPolicy:
      syncOptions:
        - CreateNamespace=true