projects:
  platform-apps:
    namespace: argocd
    description: Portfolio platform applications

    sourceRepos:
      - https://publicstaticdevnull.github.io/platform-apps/
      - https://github.com/publicstaticdevnull/platform-apps.git

    destinations:
      - namespace: "platform-*"
        server: https://kubernetes.default.svc

    clusterResourceWhitelist:
      - group: ""
        kind: Namespace

    namespaceResourceWhitelist:
      - group: "*"
        kind: "*"